name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --warnaserror # Treats warnings as errors for main branch

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Check Code Coverage
        run: |
          dotnet tool install --global coverlet.console
          dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}